<div class="col-m-6 col-m-offset-3">
    <fieldset class="fieldset admin__fieldset " id="new_blog_form">
        <!--<div class="admin__field field"
             data-ui-id="theme-edit-tabs-tab-general-section-fieldset-element-form-field-theme-path">
            <label class="label admin__field-label">
                <span>Label</span>
            </label>
            <div class="admin__field-control control">
                <div class="control-value">
                    A value
                </div>
            </div>
        </div>-->
        <div class="admin__field field ">
            <label class="label admin__field-label" for="test_input">
                <span>Blog title</span>
            </label>
            <div class="admin__field-control control">
                <input name="title" id="title" type="text" class="input-text admin__control-text"/>
            </div>
        </div>
        <div class="admin__field field ">
            <label class="label admin__field-label" for="test_input">
                <span>Url key</span>
            </label>
            <div class="admin__field-control control">
                <input name="url_key" id="url_key" type="text" class="input-text admin__control-text" required/>
            </div>
        </div>
        <div class="admin__field field ">
            <label class="label admin__field-label" for="test_input">
                <span>Content</span>
            </label>
            <div class="admin__field-control control">
                <textarea name="content" id="content" cols="50" rows="10"></textarea>
            </div>
        </div>
    </fieldset>
</div>
