<div class="blog-comment-container">
    <?php if($block->isLogin()): ?>
    <?php $customer = $block->getCustomer(); ?>
        <div class="blog-comment-form">
        <form action="../blog/comment/add" method="post" id="comment-form">
            <input type="text" name="post_id" value="<?php echo $block->getPostId(); ?>" hidden>
            <input type="text" name="user_id" value="<?php echo $customer->getId(); ?>" hidden>
            <input type="text" name="email" value="<?php echo $customer->getEmail(); ?>" hidden>
            <input type="text" name="first_name" value="<?php echo $customer->getFirstName(); ?>" hidden>
            <div class="form-input">
                <label for="">
                    <b>Comment</b>
                </label>
                <textarea name="content" id="" cols="20" rows="2" maxlength="100"></textarea>
            </div>
            <br>
            <div>
                <button id="submit">Submit</button>
            </div>
        </form>
    </div>
        <div id="note"></div>
    <?php else: ?>
        <a href="../customer/account/login">Login to comment</a>
    <?php endif; ?>
    <div class="blog-comment-list" style="margin-top: 10px">
        <h3>Comments: </h3>
        <?php foreach($block->getComments() as $comment): ?>
        <div class="post-comment" style="padding: 4px; background-color: lightgrey; margin: 10px 0">
            <div>
                <p><?php echo $block->getCustomerNameById($comment->getUserId()); ?></p>
            </div>
            <div>
                <p><?php echo $comment->getCreationTime(); ?></p>
            </div>
            <div class="comment-content" style="padding-left: 20px">
                <p><?php echo $comment->getContent(); ?></p>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php $form_url = $block->getFormAction(); ?>
<!--
<script type="text/javascript">

    require(['jquery','jquery/ui'], function($){
        $(function(){
            $(document).on('click','#submit',function (event){
                var dataFrom = $('#comment-form');
                event.preventDefault();
                var param = dataFrom.serialize();
                $.ajax({
                    type: "POST",
                    url: "<?php /*echo $form_url; */?>",
                    data: param
                }).done(function( response ) {
                    console.log(response);
                    if (response.result == 'success'){
                        $('#note').css('color','green');
                    }else {
                        $('#note').css('color','red');
                    }
                    $('#note').html(response.message);
                    document.getElementById("comment-form").reset();
                });
            });
        })
    })

</script>-->
