<style>
    .blog-post-list{
        list-style: none;
    }
</style>

<h2><?php echo __('Latest Blog Posts')?></h2>

<ul class="blog-post-list">
    <?php foreach ($block->getBlogs() as $blog): ?>
        <li class="blog-post-list-item">
            <div class="blog-post-item-title">
                <strong>
                    <a href="<?php echo $blog->getUrl(); ?>"><?php echo $blog->getTitle(); ?></a>
                </strong>
            </div>
            <div class="blog-post-item-content">
                <?php echo $blog->getContent(); ?>
            </div>
            <div class="blog-post-item-meta">
                <strong><?php echo __('Create at:'); ?></strong><?php echo $blog->getCreationTime(); ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
